name: ncs_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.1
  youtube_player_flutter: ^8.1.2
  http: ^1.1.0
  auto_route: ^7.8.4
  volume_control: ^0.1.5
  firebase_auth: ^4.14.0
  google_sign_in: ^6.1.6
  flutter_signin_button: ^2.0.0
  miniplayer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:       
  android: true
  ios: true
  image_path: "assets/stera.png"