// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAdISQctlatAFN6dfwbcs1nUSpzNyxtqg',
    appId: '1:568764222048:web:1e3f56c5ecd24cf6ded105',
    messagingSenderId: '568764222048',
    projectId: 'ncs-app-f7d0e',
    authDomain: 'ncs-app-f7d0e.firebaseapp.com',
    storageBucket: 'ncs-app-f7d0e.appspot.com',
    measurementId: 'G-3TT8W95M50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwCY5s1iiNYp0g07il93PtqjNcMXCnJ_4',
    appId: '1:568764222048:android:de67f62df977800eded105',
    messagingSenderId: '568764222048',
    projectId: 'ncs-app-f7d0e',
    storageBucket: 'ncs-app-f7d0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxl3-zpXwOwPOc4rn2X0o2GlRXKPGG_vc',
    appId: '1:568764222048:ios:3429a3a6145e30feded105',
    messagingSenderId: '568764222048',
    projectId: 'ncs-app-f7d0e',
    storageBucket: 'ncs-app-f7d0e.appspot.com',
    androidClientId: '568764222048-2bgo7m1o8cevskvh2h2gdd5peia98j2f.apps.googleusercontent.com',
    iosClientId: '568764222048-vrh0l842hiupnas9c5lkrp43p021cgrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ncsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxl3-zpXwOwPOc4rn2X0o2GlRXKPGG_vc',
    appId: '1:568764222048:ios:fb8b17665e8ddacdded105',
    messagingSenderId: '568764222048',
    projectId: 'ncs-app-f7d0e',
    storageBucket: 'ncs-app-f7d0e.appspot.com',
    androidClientId: '568764222048-2bgo7m1o8cevskvh2h2gdd5peia98j2f.apps.googleusercontent.com',
    iosClientId: '568764222048-0l2hm84sh4s0psejtufm9nkem8us77hd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ncsApp.RunnerTests',
  );
}
